# Tags: 3.1-buster-slim-arm32v7, 3.1.21-buster-slim-arm32v7, 5.0-buster-slim-arm32v7, 5.0.12-buster-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1-buster-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.21-buster-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0-buster-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0.12-buster-slim-arm32v7
