# Tags: 3.1-focal, 3.1.21-focal, 5.0-focal-amd64, 5.0.12-focal-amd64, 6.0-focal-amd64, 6.0.0-focal-amd64, 7.0-focal-amd64, 7.0.0-alpha.1-focal-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1-focal
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.21-focal
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0-focal-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0.12-focal-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0-focal-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0.0-focal-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-focal-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0.0-alpha.1-focal-amd64
