# Tags: 3.1-focal-arm32v7, 3.1.21-focal-arm32v7, 5.0-focal-arm32v7, 5.0.12-focal-arm32v7, 6.0-focal-arm32v7, 6.0.0-focal-arm32v7, 7.0-focal-arm32v7, 7.0.0-alpha.1-focal-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1-focal-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.21-focal-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0-focal-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0.12-focal-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0-focal-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0.0-focal-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-focal-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0.0-alpha.1-focal-arm32v7
