# Tags: 7.0-cbl-mariner1.0-amd64, 7.0.0-alpha.1-cbl-mariner1.0-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-cbl-mariner1.0-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0.0-alpha.1-cbl-mariner1.0-amd64
