# Tags: 3.1-bullseye-slim-arm32v7, 3.1.21-bullseye-slim-arm32v7, 5.0-bullseye-slim-arm32v7, 5.0.12-bullseye-slim-arm32v7, 6.0-bullseye-slim-arm32v7, 6.0.0-bullseye-slim-arm32v7, 7.0-bullseye-slim-arm32v7, 7.0.0-alpha.1-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.21-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0.12-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0.0-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0.0-alpha.1-bullseye-slim-arm32v7
