# Tags: 3.1-alpine3.14-arm64v8, 3.1.21-alpine3.14-arm64v8, 5.0-alpine3.14-arm64v8, 5.0.12-alpine3.14-arm64v8, 6.0-alpine3.14-arm64v8, 6.0.0-alpine3.14-arm64v8, 7.0-alpine3.14-arm64v8, 7.0.0-alpha.1-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.21-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0.12-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0.0-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0.0-alpha.1-alpine3.14-arm64v8
