# Tags: 5.0-cbl-mariner1.0-amd64, 5.0.12-cbl-mariner1.0-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0-cbl-mariner1.0-amd64
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:5.0.12-cbl-mariner1.0-amd64
